name: Feature env workflow

on:
  push:
    branches:
      - feature*

jobs:
  build-artifact:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Create and setup permissions for SSH key
      env:
        KAT_EC2_SSH_PRIVATE_KEY: ${{ secrets.KAT_EC2_SSH_PRIVATE_KEY }}
      run: |
        echo "printing present working directory"
        pwd
        echo "listing files in the directory"
        ls -l
  deploy-artifact:
    runs-on: self-hosted
    needs: build-artifact
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Create and setup permissions for SSH key
      env:
        KAT_EC2_SSH_PRIVATE_KEY: ${{ secrets.KAT_EC2_SSH_PRIVATE_KEY }}
      run: |
        pwd
        ls -l
        sudo cp index.php /var/www/html/index.php
