name: Deploy PHP App

on:
  push:
    branches:
      - feature*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.KAT_EC2_SSH_PRIVATE_KEY }}
        HOST: 44.203.64.5
        USER: ubuntu
      run: |
        ssh-keyscan $HOST >> ~/.ssh/known_hosts
        ssh -i <(echo "$PRIVATE_KEY") $USER@$HOST "rm -f /var/www/html/index.html"  # Remove index.html
        scp -i <(echo "$PRIVATE_KEY") -r * $USER@$HOST:/var/www/html/