name: Deploy PHP App

on:
  push:
    branches:
      - feature*

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Create and setup permissions for SSH key
      env:
        KAT_EC2_SSH_PRIVATE_KEY: ${{ secrets.KAT_EC2_SSH_PRIVATE_KEY }}
      run: |
        pwd
        ls -l
        sudo cp index.php /var/www/html/index.php
