name: Deploy PHP App

on:
  push:
    branches:
      - feature*

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Create and setup permissions for SSH key
      env:
        KAT_EC2_SSH_PRIVATE_KEY: ${{ secrets.KAT_EC2_SSH_PRIVATE_KEY }}
      run: |
        mkdir -p /home/runner/.ssh
        touch /home/runner/.ssh/known_hosts
        echo "$KAT_EC2_SSH_PRIVATE_KEY" > kat.pem
        chmod 600 kat.pem
        ssh-keyscan 44.203.64.5 >> ~/.ssh/known_hosts
        pwd
        ls -l
