name: Greeting on variable day

on:
  workflow_dispatch #manually run this workflow

env:
  DAY_OF_WEEK: Friday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Kat it's Friday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Kat
